[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

# Proxy rule for RSS feed to handle CORS
[[redirects]]
  from = "/api/rss-feed"
  to = "https://ai.asu.edu/taxonomy/term/1/feed"
  status = 200
  force = true
  headers = {X-From = "Netlify", Access-Control-Allow-Origin = "*"}

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
